image: node:20
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run docs:build
  artifacts:
    expire_in: 1 week
    paths:
      - .vitepress/dist
  only:
    - main